Repository magento/knowledge-base, pull requests merged in 2021-06, with the labels that each got.

#43 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Editorial, Progress: ready for review

#44 Update contribution-points.md
  docs/contribution-points.md
Labels: Editorial, Progress: ready for review

#48 Update README.md
  README.md
Labels: Progress: approved

#46 Create wiki
  wiki
Labels: New Topic, Progress: approved
