Repository magento/knowledge-base, pull requests merged in 2021-08, with the labels that each got.

#68 Correct all embedded YAML snippets to correct format
  src/how-to/general/configure-npm-to-be-able-to-use-pwa-studio.md
  src/support-tools/managed-alerts-for-magento-commerce/managed-alerts-on-magento-commerce-redis-memory-critical-alert.md
  src/support-tools/managed-alerts-for-magento-commerce/managed-alerts-on-magento-commerce-redis-memory-warning-alert.md
  src/troubleshooting/general/cached-images-are-not-loaded-after-2.2.x-to-2.3.x-upgrade.md
  src/troubleshooting/general/checking-slow-queries-and-processes-mysql.md
  src/troubleshooting/general/cron-tasks-lock-tasks-from-other-groups.md
  src/troubleshooting/general/deployment-fails-with-error-building-project-the-build-hook-failed-with-status-code-1.md
  src/troubleshooting/general/e-error-verifying-routes.yaml-error-during-staging-or-production-deploy.md
  src/troubleshooting/general/exported-products-.csv-file-does-not-appear.md
Labels: Technical, Progress: approved, partners-contribution, Partner: Vaimo

#75 Corrected URL for "/tmp mount full"
  src/troubleshooting/general/database-storage-troubleshooter-on-adobe-commerce.md
Labels: Progress: ready for review, Editorial

#71 Corrected Title
  src/best-practices/general/magento-commerce-cloud-best-practice-for-slave-connection.md
Labels: Progress: approved, partners-contribution, Partner: Vaimo

#76 Update web-api-resources-limit.md
  src/troubleshooting/known-issues-patches-attached/web-api-resources-limit.md
Labels: Progress: approved
