Repository magento/knowledge-base, pull requests merged in 2021-09, with the labels that each got.

#81 Converting filenames to the correct format
  src/support-tools/patches-available-in-qpt-tool/mdva-34680-customer-account-created-time-is-not-filtered-correctly-in-customers-grid.md
  src/support-tools/patches-available-in-qpt-tool/mdva-37068-incorrect-tax-rate-displays-on-checkout-for-virtual-products.md
  src/support-tools/patches-available-in-qpt-tool/mdva-38308-error-after-adding-vimeo-videos-to-disabled-products.md
  src/support-tools/patches-available-in-qpt-tool/mdva-38468-error-when-saving-cms-pages.md
Labels: Editorial, Progress: approved

#80 Corrected paragraph formatting V2
  src/support-tools/patches-available-in-qpt-tool/mdva-19640-magento-patch-advanced-reporting-shows-no-data.md
Labels: Progress: approved, partners-contribution, Partner: Vaimo

#83 Update block-malicious-traffic-for-magento-commerce-on-fastly-level.md
  src/how-to/general/block-malicious-traffic-for-magento-commerce-on-fastly-level.md
Labels: Progress: approved

#79 Replace Magento with Adobe Commerce
  src/best-practices/general/best-practices-for-render-blocking-resources-in-magento.md
  src/troubleshooting/general/error-purging-cache-in-admin.md
Labels: Progress: approved, partners-contribution, Partner: Vaimo

#84 Clarify enabling bundling for Commerce Cloud
  src/best-practices/general/optimize-css-and-js-files-in-magento-commerce.md
Labels: Editorial, Progress: approved, partners-contribution, Partner: Vaimo

#86 Updated typing error
  src/troubleshooting/general/elasticsuite-tracking-indices-causes-problems-with-elasticsearch.md
Labels: Progress: approved
